Repository utopia-airlines/UtopiaSearchService, pull requests merged in 2019-07, with the labels that each got.

#36 Make get-seats-for-flight endpoint return more data
  app/dao/seatDetailDao.js
Labels: complete, enhancement

#33 use esLint instead of jsLint
  .eslintrc.json
  .hound.yml
Labels: complete

#38 Upgrade dependencies
  package-lock.json
  package.json
Labels: dependencies
